from aiogram.types import ReplyKeyboardMarkup,KeyboardButton
from create_bot import data_base
con = data_base.cursor()

b1 = KeyboardButton("/Anime_info")
b2 = KeyboardButton("/Output_the_anime_list")
b3 = KeyboardButton("/AnimeByReleaseDate")
b4 = KeyboardButton("/Shonen")

kb_bot = ReplyKeyboardMarkup()
kb_bot.add(b1).add(b2).add(b3).add(b4)

#-------------------------------------------------
ab = KeyboardButton("/BackMenu")
ab1 = KeyboardButton("/Naruto")
ab2 = KeyboardButton("/DemonSlayer")
ab3 = KeyboardButton("/BlackClover")
ab4 = KeyboardButton("/HunterXHunter")
ab5 = KeyboardButton("/DeathNote")
ab6 = KeyboardButton("/TokyoGhoul")
ab7 = KeyboardButton("/CyberpunkEdgerunners")
ab8 = KeyboardButton("/ChainsawMan")
ab9 = KeyboardButton("/DarlingInTheFranXX")
ab10 = KeyboardButton("/AttackOnTitan")
ab11 = KeyboardButton("/SwordArtOnline")
ab12 = KeyboardButton("/ThePromisedNeverland")
ab13 = KeyboardButton("/TokyoRevengers")
ab14 = KeyboardButton("/Horimiya")
ab15 = KeyboardButton("/TheSevenDeadlySins")
ab16 = KeyboardButton("/ClassroomOfTheElite")
ab17 = KeyboardButton("/Kuroko'sBasketball")
ab18 = KeyboardButton("/OnePiece")
ab19 = KeyboardButton("/Bleach")
ab20 = KeyboardButton("/TheQuintessentialQuintuplets")
kb_anime = ReplyKeyboardMarkup(resize_keyboard=True)
kb_anime.add(ab,ab1,ab2,ab3,ab4,ab5,ab6,ab7,ab8,ab9,ab10,ab11,ab12,ab13).add(ab14,ab15).add(ab16,ab17).add(ab18,ab19).add(ab20)
